#!/bin/bash

echo "🔄 Setting up GitHub Pages for brmel.github.io..."

# Instructions for creating a user GitHub Pages site
echo "To use https://brmel.github.io/ directly, you need to:"
echo ""
echo "1. Create a new repository named exactly 'brmel.github.io'"
echo "2. Move your site content to that repository"
echo "3. Push to the main branch"
echo ""
echo "Commands to create the new repository:"
echo "git clone https://github.com/brmel/brmel.github.io.git"
echo "cd brmel.github.io"
echo "cp -r ../ibraverse_web/* ."
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git push origin main"
echo ""
echo "⚠️  Note: This will change your repository structure."
echo "Current working repository: https://github.com/brmel/ibraverse_web"
echo "New repository would be: https://github.com/brmel/brmel.github.io"
echo ""
echo "🎯 Recommended: Keep current setup and use custom domain ibraverse.ca"
echo "Your site is already working at: https://brmel.github.io/ibraverse_web/"
